import Head from 'next/head';
import { useRedirectPageContext } from '../lib/context';
import { useSessionContext } from '../lib/context';

export default function Home() {
  useRedirectPageContext();
  console.log(useSessionContext());

  return (
    <>
      <Head>
        <title>atlas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Home</h1>
    </>
  );
}
